### ISSUE TITLE
Обработка ошибок приводщих к завершению работы проложения

### ISSUE THREAD

**Issue by zhenyatnk** [pekabon/LogGrokCore#10]
Еще полезно было бы как то увидеть причину возникновения без отладчика, возможно трассирование информации об ошибке (стек, файл, номер строки) в DebugOutput

**Comment by zhenyatnk** [comment]
Еще полезно было бы как то увидеть причину возникновения без отладчика, возможно трассирование информации об ошибке (стек, файл, номер строки) в DebugOutput

**Comment by pekabon** [comment]
@zhenyatnk все исключения пишутся в трейсы, трейсы лежат здесь %localappdata%\loggrok2
Номера строк будут в стеке если рядом с исполняемым файлом будут лежать символы
