### ISSUE TITLE
Отображение ссылок раскрытия в компактном виде

### ISSUE THREAD

**Issue by zhenyatnk** [pekabon/LogGrokCore#7]
Сейчас ссылка разкрыть большой текст и раскрыть json добавляется как отдельная строка, 
хотелось бы убрать добавление отдельной строки, может заменить на иконки (располагать их в отдельном столбце или в строке с текстом в начале строки).

**Comment by pekabon** [comment]
Так хорошо не получается: столбец выделять жалко - он почти всегда будет пустой, иконку в начале стоки плохо (чтобы свернуть обратно- тогда надо листать в начало строки?)
Попользовался в реальных условиях с  текущим решением с разоворотом json по требованию - получается неудобно:

![image](https://user-images.githubusercontent.com/4972778/146837109-2d0c7741-77a6-403b-a5de-152b81215104.png)

Надо всегда разворачивать json и показывать "сворачивалку" внизу только если он большой по вертикали получается. Тогда и визуального мусора будет мало, и пользоваться будет удобно

На самом деле раскрывалка Json-а уже есть, только не универсальная (см в настройках формата раздел Transformations), поэтому можно посмотреть для сравнения как это выглядит:

![image](https://user-images.githubusercontent.com/4972778/146837353-0414088d-5fa9-4fc6-938b-6d7d5822757d.png)

гораздо удобней

**Comment by zhenyatnk** [comment]
да, я когда сделал раскрытие, увидел что есть трансформации
это очень похоже на то что надо, но есть некоторые неудобства
 - Раскрывается только по регекспу, а хочется для всех inline иметь такое
 - Нельзя обратить, т.е. это представление данных, а для inline хотелось бы иметь возможность просматривать в компактном виде (когда смотрим как функции приходили), для этого и используется трассировка в inline (можно трассировать сразу в раскрытом виде)

я вначале делал через контекстное меню, но в этом есть минус, не видно какие строки можно развернуть, пока не зайдешь в контекст, 
может как то подсвввечивать inline json, а в контекст добавить динамически пункт меню раскрыть/скрыть?

**Comment by pekabon** [comment]
> хотелось бы иметь возможность просматривать в компактном виде (когда смотрим как функции приходили), 
а пример есть? тут кажется глобальный рубильник нужен

**Comment by zhenyatnk** [comment]
вот в таком виде
![image](https://user-images.githubusercontent.com/12695221/146904504-a1aa11cf-2bec-4f21-a701-14f81beba968.png)
